// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// ENV_FILE lets a script target another DB, e.g. ENV_FILE=.env.supabase (prod).
// Defaults to .env (local docker).
config({ path: process.env.ENV_FILE ?? ".env" });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations use the direct connection (Supabase port 5432); the app
    // runtime uses DATABASE_URL (pooled) via the pg adapter in lib/prisma.ts.
    // Local docker has no DIRECT_URL, so it falls back to DATABASE_URL.
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL,
  },
});
